<?php
$errmsg = '';
$translate = Zend_Registry::get("translate");
?>
<?php
echo $this->partial("blocks/headercontent.phtml", array("form" => '', "id" => $this->UserID, 'twocolumn' => false));
?>

<div class="box-header with-border">
    <h3 class="box-title"><?php echo $translate->_("view_user"); ?>
    </h3>
</div>
<div class="box-body">
    
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("user_type"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["TypeName"]); ?>
        </div>
    </div>
     <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("sponsor"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["SponsorName"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("username"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["Username"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("first_name"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["FName"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("last_name"); ?>
        </label>

        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["LName"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("joining_date"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["JoiningDate"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("email"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["Email"]); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("phone"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["Phone"]); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("mobile_number"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["MobileNo"]); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("dob"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["DOB"]); ?>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("address"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["Address"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("zip_code"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["ZipCode"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("state"); ?>
        </label>
        <div class="col-sm-10">
            <?php echo $this->escape($this->UserData["StateName"]); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("profile_photo"); ?>
        </label>
        <div class="col-sm-10">
            <?php
            if(!empty( $this->UserData["Photo"])) {
                ?>
            <img src="<?php echo PUBLIC_PATH . "/profile/" . $this->UserData["Photo"]; ?>" width="50px" height="50px">
            <?php
            }
            ?>
        </div>
    </div>
    
   
    <div class="form-group">
        <label class="col-sm-3 control-label">
            <?php echo $translate->_("status"); ?>
        </label>

        <div class="col-sm-10">
            <?php
            if ($this->UserData["IsActive"] == '1') {
                echo $translate->_("active");
            } else {
                echo $translate->_("inactive");
            }
            ?>
        </div>
    </div>    
</div> 

</div>
</div>
</div>
<?php
echo $this->partial("blocks/footercontent.phtml");
?>