<div class="page-loader"></div> 
<div class="body">
    <div id="body-container">				
        <header id="header" class="header-main">	
            <nav class="navbar navbar-default navbar-fixed-top">                      
                <div class="container-fluid" style="margin-top:0px; padding-top:0px; border-top:5px solid #026670;background: #FEF9D7;" > 
                    <div class="navbar-header" >      
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">        
                            <span class="sr-only">Toggle navigation</span>        
                            <span class="icon-bar"></span>        
                            <span class="icon-bar"></span>        
                            <span class="icon-bar"></span>      
                        </button>       
                        <a class="navbar-brand" href="#">Brand</a>    
                    </div>    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">       
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a class="page-scroll" href="#body-container">Home</a></li>
                            <li ><a class="page-scroll" href="#about-section">About</a></li>
                            <li ><a class="page-scroll" href="#services-section">Services</a></li>
                            <li ><a class="page-scroll" href="#pricing-section">Pricing</a></li>
                            <!-- <li ><a class="page-scroll" href="#faq-section">Faq</a></li>-->
                            <li ><a class="page-scroll" href="#contact-section">Contact</a></li>
                            <li ><a href="myadmin/login.php" target="_blank"  style="border:1px solid #ff9c00; border-bottom:2px solid #ff9c00; padding:2px 10px; margin-top:10px;"><i class="fa fa-sign-in"></i> Login</a></li>
                            <li ><a  href="register.php" target="_blank"   style="border:1px solid #ccc; border-bottom:2px solid #ccc; padding:2px 10px; margin-top:10px; cursor:pointer "><i class="fa fa-user"></i> Sign Up</a></li>

                        </ul>    
                    </div>
                </div>
            </nav></header>
        <section  class="page" style="background:#ffff; ">       
            <div align="center" class="container-fluid top-signin">           
                <div class="container">			
                    <h2>Create your Account <strong style="color:#FCE181">FREE NOW</strong> and Start Mining</h2>
                    <form method="post" accept-charset="UTF-8" action="https://www.aweber.com/scripts/addlead.pl" class="form-inline">
                        <input type="email" name="email" class="top-text-box" required placeholder="Enter Your Email Here"> 
                        <input type="hidden" name="meta_web_form_id" value="1112671389" />
                        <input type="hidden" name="meta_split_id" value="" />
                        <input type="hidden" name="listname" value="awlist4422156" />
                        <!--<input type="hidden" name="redirect" value="https://www.aweber.com/thankyou.htm?m=default" id="redirect_425252e0adc67031a9d8954659616b78" />-->
                        <input type="hidden" name="redirect" value="http://login.coinomia.com/#/signup" id="redirect_425252e0adc67031a9d8954659616b78" />
                        <input type="hidden" name="meta_adtracking" value="My_Web_Form" />
                        <input type="hidden" name="meta_message" value="1" />
                        <input type="hidden" name="meta_required" value="email" />
                        <input type="hidden" name="meta_tooltip" value="" />

                        <input type="submit" name="submit" class="sbmit-btn" value="Join Now">
                    </form>
                </div>
            </div>

            <div class="featured-box" data-stellar-background-ratio="0.5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 wow bounceInLeft" data-wow-delay="0.2s">
                            <!-- Typed-element is configurable through the file "theme.js" -->
                            <h2><span class="top-text02">Mining has never been so Easy!
                                </span> <br>
                                <span class="top-text01">Sign up and Start Mining</span><br>
                                <span style="font-size:55px">We are mining since 2014!</span><br>
                                <span class="typed-element text-main lg-font-animated"></span> <br>
                            </h2>
                            <div class="row lead"  ><div class="col-md-4 co-sm-12" style="border-right:1px solid #000;">
                                    Begin your journey with <strong>BTC 3 TH/s or ETH .58 MH/s</strong>  Mining power.Set up Your Account and start Earning!
                                </div><div class="col-md-4 co-sm-12" style="border-right:1px solid #000;">Boost up your account with <strong>BTC 30 TH/s or ETH 5.8 MH/s</strong> and mine coins instantly! Allot the power wisely.</div><div class="col-md-4 co-sm-12">Own a Rack and get <strong>BTC 300 TH/s or ETH 57.7 MH/s</strong> of mining power. Profits earned are much More!
                                </div></div>
                        </div>
                        <div class="col-md-4 text-right wow bounceInRight" data-wow-delay="0.2s"><img src="images/coin01.png" class="img-responsive" style="padding-top:10px;">
                            <div class="get-started">

                                <a onClick="javascript:myfunction(window.location.href);" target="_blank"   class="btn btn-danger btn-lg" style="font-size:20px !important; cursor:pointer; border:2px solid #026670;">Sign Up!!!</a>
                                <div class="learn-more">or <a class="page-scroll" style="font-size:20px !important;" href="#pricing-section">learn more.</a></div>
                            </div>
                        </div>
                    </div> <!-- /.row -->
                </div> <!-- /.container -->
            </div><div class="trusted-by">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-9">
                            <h4>Add People You Know and Start Mining!</h4>
                            <small>
                                Get Paid on Their Investment.
                                <i class="fa fa-arrow-right"></i> </small>
                        </div>
                        <div class="col-sm-23"><br>
                            <a href="http://login.coinomia.com/#/login" target="_blank" class="btn-alone">WHY MINE ALONE?</a></div>

                    </div> <!-- /.row -->
                </div> <!-- /.container -->
            </div>

            <!--about us-->
            <section id="faq-section" class="page" style="background:#fff; padding-top:50px;">
                <section id="about-section"  style="background:#fff; padding-top:50px;">
                    <div class="tabs-skills" style="background:#fff;">
                        <div class="container" >
                            <div class="row" >

                                <!-- Begin tabs -->
                                <div class="col-md-6"><div class="page-header text-center wow fadeInUp" data-wow-delay="0.3s">
                                        <h1>About <span class="text-main">Us</span></h1>
                                        <div class="divider divider-icon divider-md">//</div>
                                        <p align="justify" class="lead text-gray">
                                            <strong>Coinomia</strong> is an application for mining in cryptocurrencies with any of the available gadgets, a user has. Designed to cater both new miners and power users, Coinomia requires no configuration on any device. The power allotment can be managed from anywhere and can be distributed among various cryptocurrencies.<br>
                                            <br>
                                            <strong>We are mining since early 2014, even before Ethereum was live!</strong> We have centres across the world and we have invested in latest ASIC chips and mining equipments. Our data centres are managed properly, energy efficient and we have ensured the security and maintenance with advanced tools and technology. We provide Hardware as Service/PAASto users who have an urge to mine on their own!
                                        </p>
                                    </div>
                                </div>
                                <!-- End tabs -->

                                <!-- Begin progress bars -->
                                <div class="col-md-6"><div class="page-header text-center wow fadeInUp" data-wow-delay="0.3s">
                                        <h1>About  <span class="text-main">Mining</span></h1>
                                        <div align="center" class="divider divider-icon divider-md">//</div>

                                    </div>
                                    <iframe width="100%" height="200" src="https://www.youtube.com/embed/osU5LcbYXCc" frameborder="0" gesture="" ></iframe>
                                </div>
                                <!-- End progress bars -->

                            </div> <!-- /.row -->

                        </div> <!-- /.container -->
                    </div>

                </section>
            </section>


            <section id="services-section"  style="background:#fff; padding-top:50px; margin-bottom:50px;" class="page">	<!-- Begin page header-->
                <div class="page-header-wrapper">
                    <div class="container">
                        <div class="page-header text-center wow fadeInUp" data-wow-delay="0.3s">
                            <h1>MINING  <span class="text-main"> WITH US</span></h1>
                            <div class="divider divider-icon divider-md">//</div>
                            <p class="lead text-gray">

                                Your gadget is enough for mining! 
                                Gone are those days when you have to spend your hard earned money owning and maintaining the hardware! Go ahead with cloud mining and mine with your gadget.

                            </p>
                        </div>
                    </div>
                </div>
                <!-- End page header-->

                <!-- Begin info box-1 -->
                <div class="info-box-1-wrapper">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 col-sm-6">
                                <a href="#" class="info-box-1 square-icon text-center wow zoomIn" data-wow-delay="0">
                                    <span class="info-box-icon"><i class="fa fa-database" aria-hidden="true"></i>
                                    </span>
                                    <div class="info-box-info">
                                        <h4>
                                            Multiple Data Centers Across the World
                                        </h4>
                                        <div class="divider divider-sm"></div>
                                        <p>
                                            With Multiple Datacenters across the world, we use Custom Designed Miners to mine Cryptocurrencies at Mind Crushing Speed!
                                        </p>
                                    </div>
                                </a>
                            </div>

                            <div class="col-md-3 col-sm-6">
                                <a href="#" class="info-box-1 square-icon text-center wow zoomIn" data-wow-delay="0.2s">
                                    <span class="info-box-icon"><i class="fa fa-btc"></i></span>
                                    <div class="info-box-info">
                                        <h4>
                                            Mine in Multiple Cryptocurrencies
                                        </h4>
                                        <div class="divider divider-sm"></div>
                                        <p>Not only bitcoin! We offer multiple rising cryptocurrencies. Allot the power alternately to get maximum benefits!</p>
                                    </div>
                                </a>
                            </div>

                            <div class="col-md-3 col-sm-6">
                                <a href="#" class="info-box-1 square-icon text-center wow zoomIn" data-wow-delay="0.4s">
                                    <span class="info-box-icon"><i class="fa fa-line-chart"></i></span>
                                    <div class="info-box-info">

                                        <h4>
                                            Profits beyond expectancies
                                        </h4>
                                        <div class="divider divider-sm"></div>
                                        <p>
                                            The profits can be transferred to your secure bitcoin wallet anytime you need. Profits will knock daily!
                                        </p>
                                    </div>
                                </a>
                            </div>

                            <div class="col-md-3 col-sm-6">
                                <a href="#" class="info-box-1 square-icon text-center wow zoomIn" data-wow-delay="0.6s">
                                    <span class="info-box-icon"><i class="fa fa-sign-in"></i></span>
                                    <div class="info-box-info">
                                        <h4>Kick Start <br>
                                            on the go </h4>
                                        <div class="divider divider-sm"></div>
                                        <p>
                                            Get instant Access to the Dashboard and Start Mining!</p>
                                    </div>
                                </a>
                            </div>
                        </div> <!-- /.row -->
                    </div> <!-- /.container -->
                </div></section>

            <section id="pricing-section" class="page" style="background:#fff; padding-top:50px;">

                <!-- Begin page header-->
                <div class="page-header-wrapper">
                    <div class="container">
                        <div class="page-header text-center wow fadeInUp" data-wow-delay="0.3s">
                            <h1>Our <span class="text-main">Prices</span></h1>
                            <div class="divider divider-md divider-icon">//</div>
                            <p class="lead text-gray">
                                Our packages are grouped into Two types: Pool Contract, Machine Contract, and Rack Contract . Reduced contract prices for a limited time.Allotted Mining power is worth of what you input when compared to others!
                            </p>
                        </div>
                    </div>
                </div>
                <!-- End page header-->

                <div class="more-space-l"></div>

                <!-- Begin prices -->
                <div class="prices">
                    <div class="container">
                        <div class="row">
                            <div class="price-box  col-md-4 wow flipInY" data-wow-delay="0.7s" style="margin:0px; padding:0px;">	
                                <div class="panel panel-default" style="border-left:1px solid #e2e2e2;border-bottom:1px solid #e2e2e2;">		
                                    <div class="panel-heading text-center">			
                                        <img src="images/machine-con.png" width="100">	
                                        <h3>Machine Contract</h3>		
                                    </div>		
                                    <div class="panel-body text-center"><p class="lead"><strong>$3360</strong></p>
                                    </div>			
                                    <ul class="list-group text-center">				
                                        <li class="list-group-item"><i class="text-danger"></i> Mining Power = <br>					BTC 30 TH/s <br>ETH 5.8 MH/s</li>
                                        <li class="list-group-item"><i class="text-danger"></i>Direct Referral Commissions = 8%</li>			</ul>		<div class="panel-footer text-center">			<a onClick="javascript:myfunction(window.location.href);" target="_blank" class="btn btn-lg btn-dark" style="cursor:pointer" >Sign Up Now!</a>		</div>
                                </div></div><div class="price-box price-box-featured col-md-4 wow flipInY" data-wow-delay="0.9s">	
                                <div class="panel panel-default">		
                                    <div class="panel-heading text-center">
                                        <img src="images/rack-con.png" width="100">				
                                        <h3>Rack Contract</h3>		
                                    </div>		
                                <div class="panel-body text-center"><p class="lead"><strong>$5,000</strong></p></div>			
                                       <ul class="list-group text-center">				<!--<li class="list-group-item"><i class="text-danger"></i>PV = 115</li>-->				<li class="list-group-item"><i class="text-danger"></i>Mining Power = <br>					BTC 300 TH/s <br>ETH 57.7 MH/s				</li>				<li class="list-group-item"><i class="text-danger"></i>Direct Referral Commissions = 10%</li>			</ul>		<div class="panel-footer text-center">			<a onClick="javascript:myfunction(window.location.href);" target="_blank"  class="btn btn-lg btn-main" style="cursor:pointer" >Sign Up Now!</a>		</div>		<div class="price-box-ribbon"><strong>Popular</strong></div>	</div>										</div>

                        </div> <!-- /.row -->
                    </div> <!-- /.container -->
                </div>
                <!-- End prices -->
                <div class="more-space-l"></div>
            </section>
            <section id="services-section"  style="background:#fff; padding-top:50px; margin-bottom:50px;" class="page">	
                <div class="page-header-wrapper">		
                    <div class="container">			
                        <div class="page-header text-center wow fadeInUp" data-wow-delay="0.3s">				
                            <h1>Testimonial  <span class="text-main"> </span></h1>					
                            <div class="divider divider-icon divider-md">//</div>			
                        </div>		
                    </div>	
                </div>
                <div class="info-box-1-wrapper">	
                    <div class="container">		
                        <div class="row">			
                            <div class="col-sm-12">				
                                <div class="seprator"></div>   
                                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="color: #000;">	
                                    <div class="carousel-inner">		
                                        <div class="item active">		  
                                            <div class="row" style="padding: 20px">				
                                                <button style="border: none;"><i class="fa fa-quote-left testimonial_fa" aria-hidden="true"></i></button>				
                                                <p class="testimonial_para">Lorem Ipsum ist ein einfacher Demo-Text für die Print- und Schriftindustrie. Lorem Ipsum ist in der Industrie bereits der Standard Demo-Text "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo en.</p>		
                                                <div class="row">			
                                                    <div class="col-sm-2">				
                                                        <img src="http://demos1.showcasedemos.in/jntuicem2017/html/v1/assets/images/jack.jpg" class="img-responsive" style="width: 80px">			
                                                    </div>			
                                                    <div class="col-sm-10">				
                                                        <h4><strong>Jack Andreson</strong></h4>					
                                                        <p class="testimonial_subtitle"><span>Chlinical Chemistry Technologist</span><br>						
                                                            <span>Officeal All Star Cafe</span>					
                                                        </p>			
                                                    </div>		
                                                </div>	
                                            </div>
                                        </div>
                                        <div class="item">
                                            <div class="row" style="padding: 20px">
                                                <button style="border: none;"><i class="fa fa-quote-left testimonial_fa" aria-hidden="true"></i></button>
                                                <p class="testimonial_para">Lorem Ipsum ist ein einfacher Demo-Text für die Print- und Schriftindustrie. Lorem Ipsum ist in der Industrie bereits der Standard Demo-Text "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo en.</p>
                                                <div class="row">
                                                    <div class="col-sm-2">
                                                        <img src="http://demos1.showcasedemos.in/jntuicem2017/html/v1/assets/images/kiara.jpg" class="img-responsive" style="width: 80px">
                                                    </div>
                                                    <div class="col-sm-10">
                                                        <h4><strong>Kiara Andreson</strong></h4>
                                                        <p class="testimonial_subtitle"><span>Chlinical Chemistry Technologist</span><br>
                                                            <span>Officeal All Star Cafe</span>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="controls testimonial_control pull-right">
                                    <a class="left fa fa-chevron-left btn btn-default testimonial_btn" href="#carousel-example-generic"
                                       data-slide="prev"></a>

                                    <a class="right fa fa-chevron-right btn btn-default testimonial_btn" href="#carousel-example-generic"
                                       data-slide="next"></a>
                                </div>
                            </div>


                        </div> <!-- /.row -->
                    </div> <!-- /.container -->
                </div>
            </section> 

        </section>
        <br>
        <br>
        <div class="page-header-wrapper">
            <br>
            <br>

            <!-- Begin contact section -->
            <section id="contact-section" class="page text-white parallax" data-stellar-background-ratio="0.5" style="background-image: url(img/map-bg.jpg);">
                <div class="cover"></div>

                <!-- Begin page header-->
                <div class="page-header-wrapper">
                    <div class="container">
                        <div class="page-header text-center wow bounceInDown" data-wow-delay="0.3s">
                            <h1>Contact <span class="text-main">Us</span></h1>
                            <div class="divider divider-md divider-icon divider-white">//</div>
                            <p class="lead">
                                Please feel free to write us. Our team is ready to solve all your issues and queries on the go. You can write us at <a href="cdn-cgi/l/email-protection.html" class="__cf_email__" data-cfemail="1d74737b725d7e7274737270747c337e7270">[email&#160;protected]</a> and get connected to our support team.

                            </p>
                        </div>
                    </div>
                </div>
                <!-- End page header-->

                <div class="contact wow bounceInRight" data-wow-delay="0.4s">
                    <div class="container">
                        <div class="row">

                            <div class="col-md-6">
                                <div class="contact-form">
                                    <form action="#" method="post">
                                        <div class="form-group">
                                            <input type="text" class="form-control input-lg" placeholder="Your Name" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="email" class="form-control input-lg" placeholder="E-mail" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" class="form-control input-lg" placeholder="Subject" required>
                                        </div>
                                        <div class="form-group">
                                            <textarea class="form-control input-lg" rows="5" placeholder="Message" required></textarea>
                                        </div>
                                        <button type="submit" class="btn btn-blank btn-lg wow bounceInRight" data-wow-delay="0.8s">Send Message</button>
                                    </form>
                                </div>	
                            </div>

                            <div class="col-md-6">
                                <div class="contact-info">
                                    <h3 class="contact-info-heading">Contact Info</h3>


                                    <address>
                                        <i class="fa fa-briefcase"></i> <strong>Coinomia Technologies LTD</strong><br>
                                        <i class="fa fa-map-marker"></i> 
                                        85 Great Portland Street First Floor<br/>
                                        London<br/>
                                        United Kingdom<br/>
                                        W1W 7LT<br/><br/>
                                        <i class="fa fa-phone"></i> 02031290842
                                    </address>
                                    <address>
                                        <i class="fa fa-envelope"></i> <a href="cdn-cgi/l/email-protection.html#8fe6e1e9e0cfece0e6e1e0e2e6eea1ece0e2" style="color:#fff;"><span class="__cf_email__" data-cfemail="6f060109002f0c0006010002060e410c0002" >[email&#160;protected]</span></a>
                                    </address>

                                    <div class="social-icons">
                                        <a href="cdn-cgi/l/email-protection.html#d9b0b7bfb699bab6b0b7b6b4b0b8f7bab6b4" target="_blank"><i class="fa fa-envelope fa-lg"></i></a>
                                        <a href="https://www.facebook.com/Coinomia-1077562372325251/" target="_blank"><i class="fa fa-facebook fa-lg"></i></a>
                                        <a href="https://www.youtube.com/channel/UCQA22mJPGyMx3ZTDM8uEfyw" target="_blank"><i class="fa fa-youtube fa-lg"></i></a>
                                    </div></div></div>	</div> </div></div>	<div class="more-space-xxl"></div>		</section>		<a href="#" class="scrolltotop"><i class="fa fa-long-arrow-up"></i></a> 
            <footer id="footer">
                <?php //include('include/footer.ic.php');   ?>
            </footer>			
        </div>		
    </div>	
</div>
<script>!function (e, t, r, n, c, a, l) {
        function i(t, r) {
            return r = e.createElement('div'), r.innerHTML = '<a href="' + t.replace(/"/g, '&quot;') + '"></a>', r.childNodes[0].getAttribute('href')
        }
        function o(e, t, r, n) {
            for (r = '', n = '0x' + e.substr(t, 2) | 0, t += 2; t < e.length; t += 2)
                r += String.fromCharCode('0x' + e.substr(t, 2) ^ n);
            return i(r)
        }
        try {
            for (c = e.getElementsByTagName('a'), l = '/cdn-cgi/l/email-protection#', n = 0; n < c.length; n++)
                try {
                    (t = (a = c[n]).href.indexOf(l)) > -1 && (a.href = 'mailto:' + o(a.href, t + l.length))
                } catch (e) {
                }
            for (c = e.querySelectorAll('.__cf_email__'), n = 0; n < c.length; n++)
                try {
                    (a = c[n]).parentNode.replaceChild(e.createTextNode(o(a.getAttribute('data-cfemail'), 0)), a)
                } catch (e) {
                }
        } catch (e) {
        }
    }(document);</script>
<script src="vendor/jquery/jquery-1.11.1.min.js"></script>		
<script src="vendor/bootstrap/js/bootstrap.min.js"></script>		
<script src="vendor/owl-carousel/js/owl.carousel.min.js"></script>		
<script src="vendor/stellar/js/jquery.stellar.min.js"></script>		
<script src="vendor/animations/js/wow.min.js"></script>		
<script src="vendor/classie.js"></script>		
<script src="vendor/jquery.easing.min.js"></script>		
<script src="vendor/waypoints.min.js"></script>		
<script src="vendor/jquery.counterup.min.js"></script>		
<script src="vendor/typed.js"></script>		
<script src="vendor/smoothscroll.js"></script>		
<script src="vendor/styleswitch.js"></script>		
<script src="js/theme.js"></script>		
<script src="js/custom.js"></script>		
<div class="switcher-wrapper hidden-sm hidden-xs"><div class="switcher pull-left">			
        <p>Color Scheme</p>				
        <a class="switcher-box default" href="javascript:chooseStyle('none', 60)"></a>				
        <a class="switcher-box blue" href="javascript:chooseStyle('blue-theme', 60)"></a>				
        <a class="switcher-box brown" href="javascript:chooseStyle('brown-theme', 60)"></a>				
        <a class="switcher-box green" href="javascript:chooseStyle('green-theme', 60)"></a>			
        <a class="switcher-box purple" href="javascript:chooseStyle('purple-theme', 60)"></a>	
        <a class="switcher-box yellow" href="javascript:chooseStyle('yellow-theme', 60)"></a>	
    </div>
    <div class="switcher-btn pull-right"><i class="fa fa-paint-brush"></i></div>
</div>		
<script type="text/javascript">
    $(function () {
        $(".switcher-btn").on("click", function (e) {
            e.preventDefault();
            var div = $(".switcher-wrapper");
            if (div.css("left") === "-160px") {
                $(".switcher-wrapper").animate({left: "0px"});
            } else {
                $(".switcher-wrapper").animate({
                    left: "-160px"});
            }
        });
    });</script>