<?php
$errmsg = '';
if (isset($this->errmsg) && !empty($this->errmsg)) {
    if (is_array($this->errmsg))
        $errmsg = implode("<br>", $this->errmsg);
    else
        $errmsg = $this->errmsg;
}
?>
<div class="row">
    <div class="col-xs-12">        
        <div class="dataTables_length">
            <?php
            if (!isset($this->opBarRequired)) {
                echo $this->render("blocks/operationbar.phtml");
            } else {
                echo $this->render("blocks/header.phtml");
            }
         
            ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">        
        <div class="box">
            <div id="functiondialogs">
                <?php
                if (!empty($errmsg)) {
                    ?>                                    
                    <div id="dialogcontent" title="<?php echo $this->pageTitle; ?>"> <?php echo $errmsg; ?> </div>
                    <script>
                        $(document).ready(function () {
                            $(function () {
                                $(document).ready(function () {
                                    $(function () {
                                        $("#dialogcontent").dialog({
                                            modal: true,
                                            buttons: {
                                                Ok: function () {
                                                    $(this).dialog("close");
                                                }
                                            }
                                        });
                                    });
                                });
                            });
                        });
                    </script>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <?php
        if (!empty($this->pages)) {
            echo $this->pages->deploy();
        }
        ?>
        </div>
    </div>
</div>


