<?php
$translate = Zend_Registry::get("translate");
echo $this->partial("blocks/headercontent.phtml", array("form" => $this->form));
?>
<div class="box-header with-border">
    <h3 class="box-title"><?php echo $translate->_("plan_information"); ?>
    </h3>
</div>
<div class="box-body" id="addState">
    <?php echo $this->form->getElement("PlanID"); ?>   
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("CoinID")->getLabel(); ?><span class="mendatory">*</span>
        </label>
        <div class="col-sm-10">
            <?php echo $this->form->getElement("CoinID"); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("PlanName")->getLabel(); ?><span class="mendatory">*</span>
        </label>
        <div class="col-sm-10">
            <?php echo $this->form->getElement("PlanName"); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("Description")->getLabel(); ?>
        </label>
        <div class="col-sm-10">            
            <?php echo $this->form->getElement("Description"); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("Price")->getLabel(); ?>
        </label>
        <div class="col-sm-10">            
            <?php echo $this->form->getElement("Price"); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("HashPower")->getLabel(); ?>
        </label>
        <div class="col-sm-10">            
            <?php echo $this->form->getElement("HashPower"); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->form->getElement("IsActive")->getLabel(); ?>
        </label>
        <div class="col-sm-10">            
            <?php echo $this->form->getElement("IsActive"); ?>
        </div>
    </div>
</div>
<?php
echo $this->partial("blocks/footercontent.phtml");
?>