<?php
$errmsg = '';

$translate = Zend_Registry::get("translate");

echo $this->partial("blocks/headercontent.phtml", array("id" => $this->PlanID));
?>

<div class="box-header with-border">
    <h3 class="box-title"><?php echo $translate->_("view_plan"); ?>
    </h3>
</div>
<div class="box-body">
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("coin_name"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['CoinName']); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("plan_name"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['PlanName']); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("Description"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['Description']); ?></div>
    </div>  
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("Price"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['Price']); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("HashPower"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['HashPower']); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label"><?php echo $translate->_("PowerType"); ?></label>
        <div class="col-sm-10"> <?php echo $this->escape($this->PlanData['PowerType']); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $translate->_("status"); ?>
        </label>

        <div class="col-sm-10">
            <?php
            if ($this->PlanData["IsActive"] == '1') {
                echo $translate->_("active");
            } else {
                echo $translate->_("inactive");
            }
            ?>
        </div>
    </div>
</div>
<?php
echo $this->partial("blocks/footercontent.phtml");
?>