<?php
$translate = Zend_Registry::get("translate");
echo $this->partial("blocks/headercontent.phtml", array("form" => $this->changepasswordForm, 'id' => $this->changepasswordForm, 'errmsg' => $this->errmsg, 'opBarRequired' => false));
?>
<div id="functiondialogs">
    <?php
    if (!empty($this->errmsg)) {
        ?>
        <div id="dialogcontent" style="display:none;" title="<?php echo $this->pageTitle; ?>"> <?php echo $this->errmsg; ?> </div>
        <script>
            $(document).ready(function () {
                $('.menu_nav').show();
                $(function () {
                    $("#dialogcontent").dialog({
                        modal: true,
                        buttons: {
                            Ok: function () {
                                $(this).dialog("close");
                            }
                        }
                    });
                });
            });
        </script>
        <?php
    }
    ?>
</div>
<div class="box-header with-border">
    <h3 class="box-title"><?php echo $translate->_("change_password"); ?>
    </h3>
</div>
<div class="box-body">
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->changepasswordForm->getElement("CurrentPassword")->getLabel(); ?><span class="mendatory">*</span>
        </label>
        <div class="col-sm-10"><?php echo $this->changepasswordForm->getElement("CurrentPassword"); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <input type="hidden" name="UserID" id="UserID" value="<?php echo $this->ProfileID ?>">
            <?php echo $this->changepasswordForm->getElement("Password")->getLabel(); ?><span class="mendatory">*</span></label>
        <div class="col-sm-10"><?php echo $this->changepasswordForm->getElement("Password"); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?php echo $this->changepasswordForm->getElement("ConfirmPassword")->getLabel(); ?><span class="mendatory">*</span>
        </label>
        <div class="col-sm-10"><?php echo $this->changepasswordForm->getElement("ConfirmPassword"); ?></div>
    </div> 
    <div class="form-group">
        <label class="col-sm-2 control-label">&nbsp; </label>
        <div class="col-sm-10">
            <input id="btnSave" class="btn btn-block button_save font_helvatica" type="submit" value="<?php echo $translate->_("change_password"); ?>" name="btnSave">
<input type="button" onClick="getBackData('/dashboard/dashboard/index', 'back')" value="<?php echo $translate->_("back") ?>" class="btn btn-block btn-primary button_back font_helvatica" name="btnBack" id="btnBack" />
            
        </div>
    </div>
</div>