<!DOCTYPE html>
<html lang="en">
    <head>		
        <meta charset="utf-8">		
        <meta http-equiv="X-UA-Compatible" content="IE=edge">		
        <title>Welcome Pinnacle </title>        
        <link rel="shortcut icon" type="img/png" href="img/googleg_lodp.ico"/>		
        <meta name="description" content="Coinomia">		
        <meta name="keywords" content="Coinomia" />		
        <meta name="author" content="">		
        <meta name="viewport" content="width=device-width, initial-scale=1">		
        <link href='http://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'> <!-- Body font -->		
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'> <!-- Navbar font -->		
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'> <!-- h1, h2, h3, h4, h5, h6 font -->		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/bootstrap.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/animations/css/animate.min.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/font-awesome.min.css"> <!-- Font Icons -->		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/owl-carousel/css/owl.carousel.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/owl-carousel/css/owl.theme.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/theme.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/mobile.css">		
        <link rel="stylesheet" href="<?php echo TEMPLATE_PATH ?>css/custom.css">		
        <link rel="alternate stylesheet" media="screen" title="yellow-theme" href="<?php echo TEMPLATE_PATH ?>css/demo-styles/yellow.css">
        <style>
            iframe{min-height:350px; overflow:hidden;}
            @media(max-width:540px){iframe{min-height:1950px; overflow:hidden;}}
            @media(min-width:768px) and (max-width:768px){iframe{min-height:1050px; overflow:hidden;}}
        </style>

        <script src="js/jquery/jquery-1.11.1.min.js"></script>		
        <script src="js/bootstrap.min.js"></script>		
        <script src="js/vendor/owl-carousel/js/owl.carousel.min.js"></script>		
        <script src="js/vendor/stellar/js/jquery.stellar.min.js"></script>		
        <script src="js/vendor/animations/js/wow.min.js"></script>		
        <script src="js/vendor/classie.js"></script>		
        <script src="js/vendor/jquery.easing.min.js"></script>		
        <script src="js/vendor/waypoints.min.js"></script>		
        <script src="js/vendor/jquery.counterup.min.js"></script>		
        <script src="js/vendor/typed.js"></script>		
        <script src="js/vendor/smoothscroll.js"></script>		
        <script src="js/vendor/styleswitch.js"></script>		
        <script src="js/theme.js"></script>		
        <script src="js/custom.js"></script>	
    </head>	
    <body data-spy="scroll" data-target="#main-navbar" >
        <?php echo $this->layout()->content; ?>
    </body>
</html>