<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" dir="ltr" id="minwidth" >
    <?php
    $objSession = Zend_Registry::get("session");
    ?>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="index, follow" /> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

            <title><?php echo SITE_TITLE; ?></title>
            <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
            <link rel="shortcut icon" href=" <?php //echo TEMPLATE_PATH;        ?>images/favicon.ico"  />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/style.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/bootstrap.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/jquery-ui.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/font-awesome.min.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/ionicons.min.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/AdminLTE.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/skins/_all-skins.min.css" media="all" />
            <link rel="stylesheet" type="text/css" href="<?php echo TEMPLATE_PATH ?>css/prettify.css" media="all" />

            <script language="javascript" type="text/javascript" src="/js/jquery/jquery-1.9.1.min.js"></script>
            <script language="javascript" type="text/javascript" src="/js/jquery-migrate-1.0.0.js"></script>
            <script language="javascript" type="text/javascript" src="/js/bootstrap.js"></script>
            <script language="javascript" type="text/javascript" src="/js/jquery/jquery-ui.min.js"></script>
            <script language="javascript" type="text/javascript" src="/js/jquery/jquery-ui-timepicker-addon.js"></script>

            <script language="javascript" type="text/javascript" src="/js/jquery/jquery.tablesorter.js"></script> 
	    <script language="javascript" type="text/javascript" src="/js/jquery/jquery.tablesorter.staticrow.js"></script>
            <script language="javascript" type="text/javascript" src="/js/jquery/jquery.form.js"></script>
            <script language="javascript" type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>                
            <script language="javascript" type="text/javascript" src="/js/app.js"></script>
            <script language="javascript" type="text/javascript" src="/js/demo.js"></script>
           <?php echo $this->headScript(); ?>
            <?php include_once(ROOT_PATH . "/js/loadpage.js.php"); ?>
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
    </head>

    <body style="height:100%" class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            <header class="main-header">
                <a class="logo"><span><img  height="75px" width="214px" src=<?php echo "/images/logo.png"; ?> /></span></a>

                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->

                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">

                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <?php
                                    if (!empty($objSession->Photo) && file_exists($_SERVER['DOCUMENT_ROOT'] . "/misi/public/profile/" . $objSession->Photo))
                                        $image = "/profile/" . $objSession->Photo;
                                    else
                                        $image = "/images/no-image.jpg";
                                    ?>
                                    <img src="<?php echo $image; ?>" class="user-image" alt="User Image">
                                        <span class="hidden-xs">
                                            <?php
                                            if (isset($objSession->UserName)) {
                                                echo "Welcome " . ucfirst($objSession->UserName);
                                            }
                                            ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="user-footer">                                        
                                        <a href="#profile" onclick="ActiveTab('#Home', 'profile', '/admin/profile/index')">Profile</a>
                                        <a href="#profile" onclick="ActiveTab('#Home', 'profile', '/admin/profile/changepassword')">Change Password</a>
                                        <a href="/admin/login/logout">Sign out</a>                                        
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header> 
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" style="height:auto;">
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="<?php echo $image; ?>" class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p><?php echo ucfirst($objSession->UserName); ?></p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <hr></hr>
                    <?php
                    //require_once(APPLICATION_PATH . "/classes/menu.php");
                    echo $this->render("menu.phtml");
                    ?>
                </section>
            </aside>
            <div class="content-wrapper" style="min-height: 946px;">
                <!-- Content Header (Page header) -->
                <section class="">
                    <ol class="breadcrumb"></ol>
                    <div class="loading_image" style="display:none"><img src="<?php echo TEMPLATE_PATH; ?>/images/loader/loading.gif"  /></div>
                </section>
                <section class="content" id="loadpage">
                    <?php echo $this->layout()->content; ?>
                </section>
            </div>
            
    </body>
</html>